dashboard_git_uri: # <host>/pcf-automation-status-dashboard
dashboard_git_username: # username
dashboard_git_password: # password

pcf-api:
pcf-organization:
pcf-space:
pcf-deploy-username:
pcf-deploy-password:
